import { readFileSync } from 'node:fs';
const specPath='.docs/01-requirements/2026-09-02-01-requirement-spec.md',backlogPath='.docs/01-requirements/backlog.md';
const spec=readFileSync(specPath,'utf8'),backlog=readFileSync(backlogPath,'utf8');
const stories=[...backlog.matchAll(/^#### (US-\d+)\b([\s\S]*?)(?=^#### US-|$(?![\s\S]))/gm)].map(m=>({id:m[1],body:m[2]}));
const requirements=[...spec.matchAll(/^### (FR-\d+)\b([\s\S]*?)(?=^### FR-|^## 4\.|$(?![\s\S]))/gm)].map(m=>({id:m[1],body:m[2],must:true}));
const nfr=[...spec.matchAll(/^\| (NFR-\d+) \|(.+)$/gm)].map(m=>({id:m[1],body:m[2],must:/All (NFRs|non-functional requirements)[^\n]*Must/i.test(spec)||/Must|P0/.test(m[2])}));
const legal=[...spec.matchAll(/^- \*\*(LR\d+):\*\*(.+)$/gm)].map(m=>({id:m[1],body:m[2],must:false}));
const all=[...requirements,...nfr,...legal],storyIds=new Set(stories.map(s=>s.id));
const links=b=>[...new Set(b.match(/US-\d+/g)??[])];
const duplicates=arr=>arr.filter((v,i)=>arr.indexOf(v)!==i);
const duplicateIds=[...duplicates(all.map(s=>s.id)),...duplicates(stories.map(s=>s.id))];
const malformed=stories.filter(s=>!/^\*\*Priority:\*\* P[012]\s*$/m.test(s.body)).map(s=>s.id);
const missing=all.filter(s=>s.must&&(!links(s.body).length||links(s.body).some(id=>!storyIds.has(id)))).map(s=>s.id);
const represented=new Set(all.flatMap(s=>links(s.body)));
const orphan=stories.filter(s=>/^\*\*Priority:\*\* P0\s*$/m.test(s.body)&&!represented.has(s.id)).map(s=>s.id);
const unlinked=legal.filter(s=>!s.body.includes('`rule.md`')||!/(FR-|NFR-)\d+/.test(s.body)||!links(s.body).length||links(s.body).some(id=>!storyIds.has(id))).map(s=>s.id);
const gaps=[...requirements.filter(s=>!s.body.includes('Acceptance criteria')).map(s=>`${s.id}: acceptance criteria missing`),...stories.filter(s=>!s.body.includes('Acceptance Criteria')).map(s=>`${s.id}: acceptance criteria missing`),...nfr.filter(s=>!s.body.includes('%')&&!/at least \d+/.test(s.body)).map(s=>`${s.id}: measurable target missing`)];
const categories={'MISSING BACKLOG ROWS':missing,'ORPHAN BACKLOG ROWS':orphan,'DUPLICATE IDS':duplicateIds,'MALFORMED PRIORITIES':malformed,'UNLINKED LEGAL REQUIREMENTS':unlinked,'OTHER GAPS':gaps};
const fail=Object.values(categories).some(a=>a.length);
console.log(`AUDIT: ${fail?'FAIL':'PASS'}\nSPEC: ${specPath}\nBACKLOG: ${backlogPath}`);
for(const [label,ids] of Object.entries(categories))console.log(`${label}: ${ids.join(', ')||'none'}`);
process.exitCode=fail?1:0;
