import { createRequire } from 'node:module';
import { mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import assert from 'node:assert/strict';
const supplied=process.env.PLAYWRIGHT_PACKAGE;
const require=createRequire(import.meta.url);
const { chromium }=supplied?require(supplied):require('playwright');
const output=resolve('.local/ui-check');mkdirSync(output,{recursive:true});
const origin=process.env.APP_TEST_ORIGIN??'http://localhost:3000';
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});
const errors=[];
async function choosePartner(page,name) {
 await page.getByRole('button',{name:'เลือกคู่สลับ',exact:true}).click();
 await page.getByRole('option',{name}).click();
}
try {
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 const page=await context.newPage();
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin);
 await page.getByRole('heading',{name:'เลือกบัญชีเพื่อเริ่มใช้งาน'}).waitFor();
 await page.getByRole('button',{name:/พนักงานทดสอบ A1/}).waitFor();
 await page.screenshot({path:resolve(output,'desktop-login.png'),fullPage:true,animations:'disabled'});
 await page.getByRole('button',{name:/พนักงานทดสอบ A1/}).click();
 await page.getByRole('heading',{name:'กะของฉัน',exact:true}).waitFor();
 const selectedAccounts=await (await context.request.get(`${origin}/api/demo/accounts`)).json();
 const employeeA=selectedAccounts.find(a=>a.demoProfile==='employee-a'),employeeB=selectedAccounts.find(a=>a.demoProfile==='employee-b');
 const beforeSwap=await (await context.request.get(`${origin}/api/schedules?month=2026-10`)).json();
 const beforeA=beforeSwap.assignments.find(a=>a.employee_id===employeeA.employeeId&&a.work_date==='2026-10-08');
 const beforeB=beforeSwap.assignments.find(a=>a.employee_id===employeeB.employeeId&&a.work_date==='2026-10-08');
 await page.screenshot({path:resolve(output,'desktop-schedule.png'),fullPage:true,animations:'disabled'});
 assert.equal(await page.getByText('เวอร์ชันตาราง',{exact:true}).count(),0);
 assert.equal(await page.locator('.sidebar-note').count(),0);
 assert.deepEqual(await page.locator('.team-row').allTextContents(),['ทีม A','ทีม B','ทีม C','ทีม D']);
 await page.getByRole('button',{name:'เลือกเดือน',exact:true}).click();
 assert.equal(await page.getByRole('button',{name:'มกราคม 2569',exact:true}).isDisabled(),true);
 await page.getByRole('button',{name:'ตุลาคม 2569',exact:true}).waitFor({state:'visible'});
 assert.equal(await page.getByRole('button',{name:'ตุลาคม 2569',exact:true}).getAttribute('aria-pressed'),'true');
 await page.screenshot({path:resolve(output,'desktop-month-picker.png'),fullPage:true,animations:'disabled'});
 await page.keyboard.press('ArrowRight');assert.equal(await page.locator(':focus').getAttribute('aria-label'),'พฤศจิกายน 2569');
 await page.keyboard.press('Escape');assert.equal(await page.getByRole('dialog',{name:'เลือกเดือน',exact:true}).isVisible(),false);
 await page.getByRole('button',{name:'ขอสลับกะ',exact:true}).click();
 await page.getByLabel('วันที่ต้องการสลับ',{exact:true}).waitFor();
 const originalDate=await page.getByLabel('วันที่ต้องการสลับ',{exact:true}).inputValue();
 assert.equal(await page.getByRole('button',{name:'ส่งคำขอให้หัวหน้าทีม'}).isDisabled(),true);
 await page.screenshot({path:resolve(output,'desktop-swap-empty.png'),fullPage:true,animations:'disabled'});
 const alternate=await page.getByLabel('วันที่ต้องการสลับ',{exact:true}).locator('option').filter({hasText:'11 ต.ค.'}).getAttribute('value');
 await page.getByLabel('วันที่ต้องการสลับ',{exact:true}).selectOption(alternate);
 await page.getByRole('button',{name:'เลือกคู่สลับ',exact:true}).click();
 await page.getByRole('combobox',{name:'ค้นหาคู่สลับ',exact:true}).fill('DEMO-B1');
 assert.equal(await page.getByRole('listbox',{name:'รายชื่อคู่สลับ'}).getByRole('option').count(),1,'Search matches employee code');
 await page.keyboard.press('Enter');
 assert.equal(await page.getByRole('button',{name:'ส่งคำขอให้หัวหน้าทีม'}).isEnabled(),true);
 await page.getByLabel('วันที่ต้องการสลับ',{exact:true}).selectOption(originalDate);
 await page.getByRole('button',{name:'เลือกคู่สลับ',exact:true}).waitFor();
 assert.equal(await page.locator('.partner-trigger.has-selection').count(),0,'Changing date resets partner selection');
 assert.equal(await page.getByRole('button',{name:'ส่งคำขอให้หัวหน้าทีม'}).isDisabled(),true);
 await page.getByRole('button',{name:'เลือกคู่สลับ',exact:true}).click();
 await page.screenshot({path:resolve(output,'desktop-partner-dropdown.png'),fullPage:true,animations:'disabled'});
 await page.getByRole('combobox',{name:'ค้นหาคู่สลับ'}).fill('ไม่พบพนักงานนี้');
 await page.getByText('ไม่พบชื่อหรือรหัสที่ค้นหา',{exact:true}).waitFor();
 await page.keyboard.press('Escape');assert.equal(await page.locator(':focus').getAttribute('aria-label'),'เลือกคู่สลับ');
 await choosePartner(page,'พนักงานทดสอบ B1 · ทีม B · กะเช้า');
 await page.screenshot({path:resolve(output,'desktop-swap.png'),fullPage:true,animations:'disabled'});
 for(const width of [1920,960]) {
  await page.setViewportSize({width,height:1080});
  const panel=await page.locator('.swap-panel').boundingBox(),main=await page.locator('.page-content').boundingBox(),heading=await page.locator('.swap-workspace>.page-heading').boundingBox();
  assert.ok(Math.abs(panel.x+panel.width/2-main.x-main.width/2)<2,'Swap form centered in desktop content area');
  assert.ok(Math.abs(heading.x-panel.x)<2&&Math.abs(heading.width-panel.width)<2,'Heading and form share alignment');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Intermediate/wide form overflow');
  await page.screenshot({path:resolve(output,`desktop-swap-${width}.png`),fullPage:true,animations:'disabled'});
 }
 await page.setViewportSize({width:1440,height:1000});
 // UI-only stress fixture: many long names, without submitting a synthetic request.
 const stress=await context.newPage(),stressWrites=[];stress.on('pageerror',e=>errors.push(e.message));stress.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname==='/api/requests')stressWrites.push(r.url());});
 await stress.route('**/api/swap/candidates?assignmentId=*',async route=>{
  const response=await route.fetch(),payload=await response.json(),template=payload.candidates.find(b=>b.validation.valid);
  payload.candidates=Array.from({length:120},(_,i)=>({...template,assignment_id:100000+i,name:`พนักงานสมมติสำหรับทดสอบรายชื่อจำนวนมาก ${i+1}`,employee_code:`UI-${i+1}`}));
  await route.fulfill({response,json:payload});
 });
 await stress.goto(origin);await stress.getByRole('button',{name:'ขอสลับกะ',exact:true}).click();
 await stress.getByRole('button',{name:'เลือกคู่สลับ',exact:true}).click();
 assert.equal(await stress.getByRole('listbox',{name:'รายชื่อคู่สลับ'}).getByRole('option').count(),120);
 assert.equal(await stress.locator('.partner-list').evaluate(el=>el.scrollHeight>el.clientHeight),true,'Long employee list scrolls inside dropdown');
 await stress.screenshot({path:resolve(output,'desktop-partner-many.png'),fullPage:true,animations:'disabled'});
 await stress.getByRole('combobox',{name:'ค้นหาคู่สลับ'}).fill('UI-12');
 assert.equal(await stress.getByRole('listbox',{name:'รายชื่อคู่สลับ'}).getByRole('option').count(),2);
 await stress.keyboard.press('ArrowDown');await stress.keyboard.press('Enter');
 assert.equal(await stress.getByRole('button',{name:'เลือกคู่สลับ',exact:true}).innerText().then(text=>text.includes('UI-120')),true);
 await stress.setViewportSize({width:390,height:844});await stress.getByRole('button',{name:'เลือกคู่สลับ',exact:true}).click();
 await stress.getByRole('combobox',{name:'ค้นหาคู่สลับ'}).fill('UI-120');
 const stressPopup=await stress.getByRole('dialog',{name:'เลือกคู่สลับ',exact:true}).boundingBox();
 assert.ok(stressPopup.x>=0&&stressPopup.x+stressPopup.width<=390&&stressPopup.y>=0&&stressPopup.y+stressPopup.height<=844,'Employee chooser fits mobile viewport');
 await stress.screenshot({path:resolve(output,'mobile-partner-many.png'),fullPage:true,animations:'disabled'});
 await stress.keyboard.press('Escape');assert.deepEqual(stressWrites,[]);await stress.close();
 await page.getByRole('button',{name:'ส่งคำขอให้หัวหน้าทีม'}).click();
 await page.getByRole('heading',{name:'คำขอของฉัน',exact:true}).waitFor();
 await page.getByRole('button',{name:'ดูรายละเอียด',exact:true}).click();
 await page.getByRole('heading',{name:'รายละเอียดกะทั้งสองคน',exact:true}).waitFor();
 await page.screenshot({path:resolve(output,'desktop-request-details.png'),fullPage:true,animations:'disabled'});
 await page.getByRole('button',{name:'ซ่อนรายละเอียด',exact:true}).click();
 await page.reload();
 await page.getByRole('button',{name:'คำขอของฉัน',exact:true}).click();
 await page.getByRole('heading',{name:/สลับกะ · 8/}).waitFor();
 const getAccount=async pattern=>{
  const c=await browser.newContext({viewport:{width:1440,height:1000}}),p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));
  await p.goto(origin);await p.getByRole('button',{name:pattern}).click();return {c,p};
 };
 const a=await getAccount(/หัวหน้าทดสอบ A0/),b=await getAccount(/หัวหน้าทดสอบ B0/);
 const decisionWrites=[];a.p.on('request',r=>{if(r.method()==='POST'&&/\/decisions$/.test(new URL(r.url()).pathname))decisionWrites.push(r.url());});
 await a.p.getByRole('button',{name:'ตรวจและอนุมัติ'}).click();
 await a.p.getByRole('button',{name:'กลับ',exact:true}).click();
 assert.equal(await a.p.locator(':focus').innerText(),'ตรวจและอนุมัติ','Cancel restores focus to the initiating action');
 await a.p.getByRole('button',{name:'ไม่อนุมัติ',exact:true}).click();
 assert.equal(await a.p.getByRole('textbox',{name:'เหตุผล',exact:true}).evaluate(el=>el.checkValidity()),false,'Rejection still requires a reason');
 await a.p.screenshot({path:resolve(output,'desktop-rejection-confirm.png'),fullPage:true,animations:'disabled'});
 await a.p.getByRole('button',{name:'กลับ',exact:true}).click();
 assert.equal(await a.p.locator(':focus').innerText(),'ไม่อนุมัติ');assert.deepEqual(decisionWrites,[],'Review and cancel never submit a decision');
 await a.p.getByRole('button',{name:'ตรวจและอนุมัติ'}).click();
 await a.p.screenshot({path:resolve(output,'desktop-approval-confirm.png'),fullPage:true,animations:'disabled'});
 await a.p.getByRole('button',{name:'ยืนยันอนุมัติ',exact:true}).click();
 await a.p.getByText('รอ หัวหน้าทดสอบ B0 · ตารางยังไม่เปลี่ยน',{exact:true}).waitFor();
 await page.getByRole('button',{name:'โหลดล่าสุด',exact:true}).click();
 await page.getByText('รอ หัวหน้าทดสอบ B0 · ตารางยังไม่เปลี่ยน',{exact:true}).waitFor();
 await b.p.getByRole('button',{name:'โหลดล่าสุด',exact:true}).click();
 await b.p.getByRole('button',{name:'ตรวจและอนุมัติ'}).click();
 await b.p.getByRole('button',{name:'ยืนยันอนุมัติ',exact:true}).click();
 await b.p.getByText('อนุมัติครบสองฝ่ายแล้ว ตารางกะทั้งสองคนอัปเดตเรียบร้อย',{exact:true}).waitFor();
 await b.p.screenshot({path:resolve(output,'desktop-approved.png'),fullPage:true,animations:'disabled'});
 await page.reload();await page.getByRole('button',{name:'คำขอของฉัน',exact:true}).click();
 await page.getByText('อนุมัติครบสองฝ่ายแล้ว ตารางกะทั้งสองคนอัปเดตเรียบร้อย',{exact:true}).waitFor();
 await page.screenshot({path:resolve(output,'desktop-my-requests.png'),fullPage:true,animations:'disabled'});
 await page.getByRole('button',{name:'ประวัติของฉัน',exact:true}).click();await page.getByRole('heading',{name:'ประวัติการทำรายการของฉัน',exact:true}).waitFor();
 assert.equal(await page.locator('.personal-history-row').count(),1,'Approval actions do not duplicate the employee submission history');
 assert.equal(await page.locator('.personal-history-row').first().innerText().then(text=>text.includes('8 ต.ค. 2569')&&text.includes('พนักงานทดสอบ B1')),true);
 for(const text of ['เปลี่ยนตารางกะทั้งสองคน','บันทึกการอนุมัติ','หัวหน้าทดสอบ A0','หัวหน้าทดสอบ B0'])assert.equal(await page.getByText(text,{exact:true}).count(),0);
 for(const text of ['เปิดดูตารางกะ','ออกจากบัญชีเดโม','เข้าใช้งานบัญชีเดโม','รายละเอียดหลักฐาน'])assert.equal(await page.getByText(text,{exact:true}).count(),0,'History contains request activity only');
 await page.screenshot({path:resolve(output,'desktop-history.png'),fullPage:true,animations:'disabled'});
 const afterSwap=await (await context.request.get(`${origin}/api/schedules?month=2026-10`)).json();
 const secondSession=await (await b.c.request.get(`${origin}/api/schedules?month=2026-10`)).json();
 assert.equal(afterSwap.schedule.version,secondSession.schedule.version,'Independent browsers see the same schedule version');
 for(const [own,incoming] of [[beforeA,beforeB],[beforeB,beforeA]]) {
  const updated=afterSwap.assignments.find(a=>a.assignment_id===own.assignment_id);
  assert.equal(updated.shift_code,incoming.shift_code);assert.equal(updated.version,own.version+1);
 }
 await page.getByRole('button',{name:'กะของฉัน',exact:true}).click();
 await page.locator('.own-row td').nth(7).locator('button.grid-shift').waitFor();
 assert.equal(await page.locator('.own-row td').nth(7).locator('button.grid-shift').innerText(),beforeB.shift_code,'Table shows the persisted incoming shift');
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),phone=await mobile.newPage();
 phone.on('pageerror',e=>errors.push(e.message));
 await phone.goto(origin);await phone.getByRole('button',{name:/พนักงานทดสอบ A1/}).click();
 await phone.getByRole('heading',{name:'กะของฉัน',exact:true}).waitFor();
 assert.equal(await phone.evaluate(width=>document.documentElement.scrollWidth<=width,phone.viewportSize().width),true,'Mobile page overflow');
 await phone.screenshot({path:resolve(output,'mobile-schedule.png'),fullPage:true,animations:'disabled'});
 await phone.getByRole('button',{name:'เลือกเดือน',exact:true}).click();
 const popup=await phone.getByRole('dialog',{name:'เลือกเดือน',exact:true}).boundingBox();
 assert.ok(popup.x>=0&&popup.x+popup.width<=390&&popup.y>=0&&popup.y+popup.height<=844,'Mobile month chooser fits viewport');
 await phone.screenshot({path:resolve(output,'mobile-month-picker.png'),fullPage:true,animations:'disabled'});
 await phone.getByRole('button',{name:'ปิดตัวเลือกเดือน',exact:true}).click();
 await phone.getByRole('button',{name:'เปิดเมนู'}).click();await phone.getByRole('button',{name:'คำขอของฉัน',exact:true}).click();
 await phone.getByText('อนุมัติครบสองฝ่ายแล้ว ตารางกะทั้งสองคนอัปเดตเรียบร้อย',{exact:true}).waitFor();
 await phone.screenshot({path:resolve(output,'mobile-approved.png'),fullPage:true,animations:'disabled'});
 // Repeat the full workflow on a different work date using mobile layouts.
 await phone.getByRole('button',{name:'เปิดเมนู'}).click();await phone.getByRole('button',{name:'กะของฉัน',exact:true}).click();
 await phone.getByRole('button',{name:/11 ต.ค. 2569 .* เลือกสลับกะ$/}).click();
 await phone.getByRole('button',{name:'เลือกคู่สลับ',exact:true}).click();
 await phone.screenshot({path:resolve(output,'mobile-partner-dropdown.png'),fullPage:true,animations:'disabled'});
 await phone.getByRole('option',{name:/พนักงานทดสอบ B1/}).click();
 assert.equal(await phone.evaluate(width=>document.documentElement.scrollWidth<=width,phone.viewportSize().width),true,'Mobile swap form overflow');
 await phone.screenshot({path:resolve(output,'mobile-swap.png'),fullPage:true,animations:'disabled'});
 await phone.getByRole('button',{name:'ส่งคำขอให้หัวหน้าทีม'}).click();
 await phone.getByRole('heading',{name:/สลับกะ · 11/}).waitFor();
 for(const approver of [a,b]) {
  await approver.p.setViewportSize({width:390,height:844});await approver.p.reload();
  await approver.p.getByRole('button',{name:'ตรวจและอนุมัติ'}).click();
  assert.equal(await approver.p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Approval confirmation fits mobile');
  await approver.p.screenshot({path:resolve(output,approver===a?'mobile-first-approval-confirm.png':'mobile-final-approval-confirm.png'),fullPage:true,animations:'disabled'});
  await approver.p.getByRole('button',{name:'ยืนยันอนุมัติ',exact:true}).click();
  await approver.p.getByRole('button',{name:'ยืนยันอนุมัติ',exact:true}).waitFor({state:'hidden'});
 }
 await phone.reload();await phone.getByRole('button',{name:'เปิดเมนู'}).click();await phone.getByRole('button',{name:'คำขอของฉัน',exact:true}).click();
 const mobileRequest=phone.locator('section.employee-request').filter({has:phone.getByRole('heading',{name:/สลับกะ · 11/})});
 await mobileRequest.getByText('อนุมัติครบสองฝ่ายแล้ว ตารางกะทั้งสองคนอัปเดตเรียบร้อย',{exact:true}).waitFor();
 assert.equal(await phone.evaluate(width=>document.documentElement.scrollWidth<=width,phone.viewportSize().width),true,'Mobile completed request overflow');
 await phone.screenshot({path:resolve(output,'mobile-full-workflow.png'),fullPage:true,animations:'disabled'});
 await mobileRequest.getByRole('button',{name:'ดูรายละเอียด',exact:true}).click();
 await mobileRequest.getByRole('heading',{name:'รายละเอียดกะทั้งสองคน',exact:true}).waitFor();
 assert.equal(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'Mobile request details fit viewport');
 await phone.screenshot({path:resolve(output,'mobile-request-details.png'),fullPage:true,animations:'disabled'});
 await phone.getByRole('button',{name:'เปิดเมนู'}).click();await phone.getByRole('button',{name:'ประวัติของฉัน',exact:true}).click();
 await phone.getByRole('heading',{name:'ประวัติการทำรายการของฉัน',exact:true}).waitFor();
 assert.equal(await phone.locator('.personal-history-row').count(),2,'Two submissions remain two history entries after both approvals');
 assert.equal(await phone.locator('.personal-history-row').first().innerText().then(text=>text.includes('11 ต.ค. 2569')),true,'Newest personal action is first');
 await phone.screenshot({path:resolve(output,'mobile-history.png'),fullPage:true,animations:'disabled'});
 // Reverse direction: employee B requests, supervisor B first, then A.
 const reverse=await getAccount(/พนักงานทดสอบ B1/);
 await reverse.p.getByRole('heading',{name:'กะของฉัน',exact:true}).waitFor();
 await reverse.p.getByRole('button',{name:'เลือกเดือน',exact:true}).click();await reverse.p.getByRole('button',{name:'พฤศจิกายน 2569',exact:true}).click();
 await reverse.p.getByRole('button',{name:/^4 พ.ย. 2569 .* เลือกสลับกะ$/}).click();
 await choosePartner(reverse.p,/พนักงานทดสอบ A1/);
 await reverse.p.getByRole('button',{name:'ส่งคำขอให้หัวหน้าทีม'}).click();
 await reverse.p.getByText('รอ หัวหน้าทดสอบ B0 · ตารางยังไม่เปลี่ยน',{exact:true}).waitFor();
 for(const approver of [b,a]) {
  await approver.p.reload();await approver.p.getByRole('button',{name:'ตรวจและอนุมัติ'}).click();await approver.p.getByRole('button',{name:'ยืนยันอนุมัติ',exact:true}).click();
  await approver.p.getByRole('button',{name:'ยืนยันอนุมัติ',exact:true}).waitFor({state:'hidden'});
 }
 await reverse.p.reload();await reverse.p.getByRole('button',{name:'คำขอของฉัน',exact:true}).click();
 await reverse.p.getByText('อนุมัติครบสองฝ่ายแล้ว ตารางกะทั้งสองคนอัปเดตเรียบร้อย',{exact:true}).waitFor();
 await reverse.p.screenshot({path:resolve(output,'desktop-reverse-approved.png'),fullPage:true,animations:'disabled'});
 assert.deepEqual(errors,[],'Browser runtime errors');
 console.log('BROWSER PASS: desktop/mobile A → B and reverse B → A, independent sessions, request refresh, both approvals, approved refresh and audit.');
} finally {await browser.close();}
